language: node_js
node_js:
  - 8
before_script:
  - npm i -g
install:
  - npm run build
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
