language: node_js
node_js:
  - 8
before_script:
  - npm i -g

cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "dd57e8a0c05eb189c28b6045731064ee383d0689"
  keep-history: true
  on:
    branch: master
